Setting up bootstrap
Frames-Proj/frames pull request #10
Opened 2017-02-08 22:12 UTC by holeyness

2017-02-09 17:36 UTC, nicholasyan commented
Looks good to me.

2017-02-11 18:44 UTC, ethanpailes commented
Is it possible to configure bootstrap easily with npm, or is the state of the art basically just copying the files?

2017-02-11 18:45 UTC, ethanpailes requested changes

2017-02-11 18:45 UTC, ethanpailes commented on app/tsconfig.json
> +     "src/ts/bootstrap.js"
js files should not be part of the list of files for the typescript compiler to build. Please remove this line.

2017-02-13 01:05 UTC, holeyness commented
Two things: 
1. bootstrap can be packaged with npm, but then it's installed under like node_modules, so the importing of css and scripts file is more of a pain, not sure what the correct solution for that is.
2. As for the js file, if we use the copy paste method, like whats the pattern there? Cuz nothing in the js folder is committed

2017-02-13 17:40 UTC, ethanpailes commented
So it sounds like the plan is just to put it in the js directory and ungitignore it.

2017-02-14 04:07 UTC, merged