Video cache
Frames-Proj/frames pull request #107
Opened 2017-04-26 16:06 UTC by GrahamGoudeau

2017-04-26 16:19 UTC, GrahamGoudeau commented
Closes #104

2017-04-27 14:50 UTC, ethanpailes commented
This looks really clean.

It looks like the video cache only works in-memory, and most of the value-added from having a history page is that we don't have to re-download videos after restarting the app. The video files are going to be there on disk anyway, so it is worth listing them.

If you could add the ability to serialize the video metadata and access time to some location in the CONFIG.APP_HOME_DIR, and then read it on startup, that would be ideal.

2017-04-27 14:51 UTC, ethanpailes requested changes
See my comment in the main thread about serializing the cache to disk.

2017-04-27 14:51 UTC, ethanpailes commented on app/client/ts/video-cache.ts
> +            if (this.numEntries + 1 > CONFIG.MAX_CACHE_SIZE) {
I like the garbage-collection bit.

2017-04-27 15:22 UTC, nicholasyan commented
With the changes @ethanpailes was talking about, looks good to me.

2017-04-29 01:49 UTC, ethanpailes commented
I just merged #114 BTW

2017-04-29 16:03 UTC, ethanpailes commented on app/client/ts/video-model.ts
> +export class Video implements Drop {
Video really is the main thing this module exports. You can have both a default export and standard exports.

2017-04-29 16:21 UTC, ethanpailes requested changes

2017-04-29 16:21 UTC, ethanpailes commented on app/client/ts/video-cache.ts
> +    stateToString(): string {
What is going on here?

2017-04-29 16:21 UTC, ethanpailes commented on app/client/ts/video-cache.ts
> +    private static async readFromDisk(longName): Promise<Maybe<CacheStateStringy>> {
What does Nothing represent that is different than an empty CacheStateStringy object? A comment explaining might be a little nice. (non merge blocking).

2017-04-29 16:21 UTC, ethanpailes commented on app/client/ts/video-cache.ts
> +        const homeDir: DnsHomeDirectory = await safeClient.dns.getHomeDirectory(longName, CONFIG.SERVICE_NAME);
I may be misunderstanding what this function is supposed to do, but why is it touching the SafeNET? The cache metadata should be stored locally to describe the files that actually exist on disk on your current machine. It does not make any sense to download a video on my linux box, update my cache on the SafeNET, then move to my mac and try to read one of the local files that I've downloaded onto my linux box.

2017-04-29 16:21 UTC, ethanpailes commented on app/client/ts/video-cache.ts
> +    async persistOnDisk() {
Same concern as above. I think this stuff should really be mucking about with files under the CONFIG.SAFE_APP_DIR directory.

2017-05-19 02:30 UTC, ethanpailes commented
It doesn't look like this will get maintained.

2017-05-19 02:30 UTC, closed without merging